- name: crete the cart 
  hosts: cart
  become: yes
  tasks:
    - name: disable old nodejs and enable new node js 
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

    - name: install the node js
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create the directory 
      ansible.builtin.user:
        name: roboshop

    - name: remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download the cart application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /tmp

    - name: unzip the cart application
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: Install dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: copy the cart service
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: deamon realod and start
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start and enable cart
      ansible.builtin.service:
        name: cart
        state: restarted
        enabled: yes
